In [3]:
import pandas as pd
import numpy as np
import csv

df = pd.read_csv("C:/Users/OMISTAJA/Downloads/ObesityDataSet_raw_and_data_sinthetic.csv")
type(df)

pandas.core.frame.DataFrame

In [4]:
df = df.astype({'Age' : 'int'})
df.head(10)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,29,Male,1.62,53.0,Sometimes,yes,2.0,3.0,no,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,23,Female,1.50,55.0,Sometimes,yes,3.0,3.0,no,no,2.0,yes,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,22,Male,1.64,53.0,Sometimes,no,2.0,3.0,no,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,24,Male,1.78,64.0,Frequently,yes,3.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
9,22,Male,1.72,68.0,no,yes,2.0,3.0,no,no,2.0,yes,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [5]:
df.shape[0]
df.info()
df.shape
df.shape[1]
df.columns
df.index
df.values

column_data_types = df.dtypes
print(column_data_types)

column_data_type = df['Age'].dtype
print(column_data_type)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   int64
 1   Gender                          2111 non-null   object
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(7), int64(1), object(9)
memory usage: 280.5+ KB
Age                                 int64
Gender                             object
Height                            float64
Weight                            float64
CALC                               object
FAVC                               object
FCVC                              float64
NCP                               float64
SCC                                object
SMOKE                              object
CH2O                              float64
family_history_with_overweight     object
FAF                               float64
TUE                               float64
CAEC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object
int64

In [6]:
df.sort_values("Age")

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
415,14,Male,1.710000,72.000000,no,yes,3.000000,3.0,no,no,3.000000,yes,2.000000,1.000000,Sometimes,Walking,Normal_Weight
116,15,Female,1.650000,86.000000,no,yes,3.000000,3.0,no,no,1.000000,yes,3.000000,2.000000,Sometimes,Walking,Obesity_Type_I
959,16,Female,1.613921,66.738769,no,yes,2.206399,1.0,yes,no,2.000000,yes,0.948930,1.772463,Sometimes,Public_Transportation,Overweight_Level_I
876,16,Female,1.608914,65.000000,no,yes,1.321028,1.0,yes,no,2.000000,yes,0.371452,0.965604,Sometimes,Public_Transportation,Overweight_Level_I
953,16,Female,1.616533,65.062945,no,yes,2.388168,1.0,yes,no,1.438018,yes,0.110887,1.165817,Sometimes,Public_Transportation,Overweight_Level_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,55,Male,1.657221,80.993213,no,yes,2.000000,3.0,no,no,2.000000,yes,1.000000,0.000000,Sometimes,Automobile,Overweight_Level_II
1158,55,Male,1.673394,80.400306,no,yes,2.000000,3.0,no,no,2.000000,yes,1.000000,0.000000,Sometimes,Automobile,Overweight_Level_II
92,55,Male,1.780000,84.000000,Frequently,no,3.000000,4.0,yes,no,3.000000,yes,3.000000,0.000000,Frequently,Walking,Overweight_Level_I
252,56,Male,1.790000,90.000000,Frequently,no,2.000000,3.0,no,yes,2.000000,yes,1.000000,0.000000,Sometimes,Automobile,Overweight_Level_II
133,61,Female,1.650000,66.000000,Frequently,yes,3.000000,3.0,no,no,2.000000,no,1.000000,1.000000,Always,Public_Transportation,Normal_Weight

In [7]:
df.sort_values("Weight", ascending=False).round(2)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
344,18,Male,1.87,173.00,Sometimes,yes,3.00,3.00,no,no,2.00,yes,2.00,1.00,Frequently,Public_Transportation,Obesity_Type_III
502,21,Female,1.84,165.06,Sometimes,yes,3.00,3.00,no,no,2.41,yes,0.10,0.48,Sometimes,Public_Transportation,Obesity_Type_III
1898,19,Female,1.79,160.94,Sometimes,yes,3.00,3.00,no,no,2.07,yes,1.99,0.95,Sometimes,Public_Transportation,Obesity_Type_III
1910,21,Female,1.80,160.64,Sometimes,yes,3.00,3.00,no,no,2.40,yes,0.43,0.64,Sometimes,Public_Transportation,Obesity_Type_III
1838,20,Female,1.81,155.87,Sometimes,yes,3.00,3.00,no,no,2.42,yes,0.95,0.57,Sometimes,Public_Transportation,Obesity_Type_III
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,18,Female,1.57,39.85,Sometimes,yes,1.21,1.72,no,no,1.18,no,0.68,2.00,Sometimes,Public_Transportation,Insufficient_Weight
636,19,Female,1.56,39.70,Sometimes,yes,1.89,2.22,no,no,2.01,no,2.08,1.68,Sometimes,Public_Transportation,Insufficient_Weight
589,19,Female,1.53,39.37,Sometimes,yes,1.52,3.00,no,no,1.98,no,2.31,0.72,Sometimes,Public_Transportation,Insufficient_Weight
725,19,Female,1.54,39.10,Sometimes,yes,1.12,3.00,no,no,2.00,no,2.43,1.63,Sometimes,Public_Transportation,Insufficient_Weight
395,20,Female,1.54,39.00,Sometimes,yes,1.00,3.00,no,no,2.00,yes,3.00,2.00,Sometimes,Public_Transportation,Insufficient_Weight

In [8]:
df.sort_values(["Weight", "Height"], ascending=[True, False]).round(2)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
395,20,Female,1.54,39.00,Sometimes,yes,1.00,3.00,no,no,2.00,yes,3.00,2.00,Sometimes,Public_Transportation,Insufficient_Weight
725,19,Female,1.54,39.10,Sometimes,yes,1.12,3.00,no,no,2.00,no,2.43,1.63,Sometimes,Public_Transportation,Insufficient_Weight
589,19,Female,1.53,39.37,Sometimes,yes,1.52,3.00,no,no,1.98,no,2.31,0.72,Sometimes,Public_Transportation,Insufficient_Weight
636,19,Female,1.56,39.70,Sometimes,yes,1.89,2.22,no,no,2.01,no,2.08,1.68,Sometimes,Public_Transportation,Insufficient_Weight
588,18,Female,1.57,39.85,Sometimes,yes,1.21,1.72,no,no,1.18,no,0.68,2.00,Sometimes,Public_Transportation,Insufficient_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1838,20,Female,1.81,155.87,Sometimes,yes,3.00,3.00,no,no,2.42,yes,0.95,0.57,Sometimes,Public_Transportation,Obesity_Type_III
1910,21,Female,1.80,160.64,Sometimes,yes,3.00,3.00,no,no,2.40,yes,0.43,0.64,Sometimes,Public_Transportation,Obesity_Type_III
1898,19,Female,1.79,160.94,Sometimes,yes,3.00,3.00,no,no,2.07,yes,1.99,0.95,Sometimes,Public_Transportation,Obesity_Type_III
502,21,Female,1.84,165.06,Sometimes,yes,3.00,3.00,no,no,2.41,yes,0.10,0.48,Sometimes,Public_Transportation,Obesity_Type_III
344,18,Male,1.87,173.00,Sometimes,yes,3.00,3.00,no,no,2.00,yes,2.00,1.00,Frequently,Public_Transportation,Obesity_Type_III

In [9]:
subset_df = df[["Age", "Height", "Weight"]].round(2)
print(subset_df)

      Age  Height  Weight
0      21    1.62   64.00
1      21    1.52   56.00
2      23    1.80   77.00
3      27    1.80   87.00
4      22    1.78   89.80
...   ...     ...     ...
2106   20    1.71  131.41
2107   21    1.75  133.74
2108   22    1.75  133.69
2109   24    1.74  133.35
2110   23    1.74  133.47

[2111 rows x 3 columns]

In [10]:
subset_df0 = df[df['Weight'] > 100]
print(subset_df0)

      Age  Gender    Height      Weight        CALC FAVC  FCVC  NCP  SCC  \
10     26    Male  1.850000  105.000000   Sometimes  yes   3.0  3.0   no
16     27    Male  1.930000  102.000000   Sometimes  yes   2.0  1.0   no
68     30    Male  1.760000  112.000000  Frequently  yes   1.0  3.0  yes
134    30    Male  1.770000  109.000000   Sometimes  yes   3.0  3.0   no
165    30    Male  1.920000  130.000000   Sometimes   no   2.0  3.0   no
...   ...     ...       ...         ...         ...  ...   ...  ...  ...
2106   20  Female  1.710730  131.408528   Sometimes  yes   3.0  3.0   no
2107   21  Female  1.748584  133.742943   Sometimes  yes   3.0  3.0   no
2108   22  Female  1.752206  133.689352   Sometimes  yes   3.0  3.0   no
2109   24  Female  1.739450  133.346641   Sometimes  yes   3.0  3.0   no
2110   23  Female  1.738836  133.472641   Sometimes  yes   3.0  3.0   no

     SMOKE      CH2O family_history_with_overweight       FAF       TUE  \
10      no  3.000000                            yes  2.000000  2.000000
16      no  1.000000                            yes  1.000000  0.000000
68     yes  2.000000                            yes  0.000000  0.000000
134     no  1.000000                            yes  2.000000  0.000000
165    yes  1.000000                            yes  1.000000  0.000000
...    ...       ...                            ...       ...       ...
2106    no  1.728139                            yes  1.676269  0.906247
2107    no  2.005130                            yes  1.341390  0.599270
2108    no  2.054193                            yes  1.414209  0.646288
2109    no  2.852339                            yes  1.139107  0.586035
2110    no  2.863513                            yes  1.026452  0.714137

            CAEC                 MTRANS           NObeyesdad
10    Frequently  Public_Transportation       Obesity_Type_I
16     Sometimes  Public_Transportation  Overweight_Level_II
68            no             Automobile      Obesity_Type_II
134    Sometimes             Automobile       Obesity_Type_I
165    Sometimes  Public_Transportation      Obesity_Type_II
...          ...                    ...                  ...
2106   Sometimes  Public_Transportation     Obesity_Type_III
2107   Sometimes  Public_Transportation     Obesity_Type_III
2108   Sometimes  Public_Transportation     Obesity_Type_III
2109   Sometimes  Public_Transportation     Obesity_Type_III
2110   Sometimes  Public_Transportation     Obesity_Type_III

[716 rows x 17 columns]

In [11]:
subset_df1 = df['Weight'] > 100
subset_df2 = df['SMOKE'] == "yes"
subset_df3 = df[subset_df1 & subset_df2]
subset_df3.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
68,30,Male,1.76,112.0,Frequently,yes,1.0,3.0,yes,yes,2.0,yes,0.0,0.0,no,Automobile,Obesity_Type_II
165,30,Male,1.92,130.0,Sometimes,no,2.0,3.0,no,yes,1.0,yes,1.0,0.0,Sometimes,Public_Transportation,Obesity_Type_II
202,26,Female,1.56,102.0,Sometimes,yes,3.0,3.0,no,yes,1.0,yes,0.0,1.0,Sometimes,Public_Transportation,Obesity_Type_III
294,18,Male,1.86,110.0,Sometimes,yes,2.0,1.0,no,yes,2.0,yes,1.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I
305,23,Male,1.75,120.0,Sometimes,yes,2.0,3.0,no,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Obesity_Type_II

In [13]:
def categorize_weight(Weight):
    if Weight < 50:
        return 'Low'
    elif Weight < 80:
        return 'Medium'
    else:
        return 'High'
        

df['weight_group'] = df['Weight'].apply(categorize_weight)
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,weight_group
0,21,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Medium
1,21,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Medium
2,23,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Medium
3,27,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I,High
4,22,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,High